
blank_issues_enabled: false
contact_links:
  - name: Ghid și întrebări frecvente
    url: https://github.com/cnecrea/hidroelectrica/blob/main/FAQ.md
    about: Documentație și întrebări frecvente” oferă informații detaliate despre utilizarea, configurarea și funcționalitățile integrării, precum și răspunsuri la cele mai comune întrebări ale utilizatorilor.
  - name: Suport
    url: https://github.com/cnecrea/hidroelectrica/discussions
    about: Dacă problema ta nu se potrivește cu un template, poți cere ajutor în secțiunea de discuții.

